### ISSUE TITLE
Select all and delete doesn't work: "it's not allowed to delete answer placeholder"

### ISSUE THREAD

**Issue by evgraph** [evgraph/CheckIOPyCharmPlugin#37]
Don't set ReadonlyFragmentModificationHandler  in StudyUtils#drawAllWindows in CheckIO Projects

**Comment by ktisha** [comment]
fixed in 831366cc1a2f8235f4d26d2b935e9074bb088600 (this repo)

and e86e1256ded29595c66608e16783371f99df331a (community one)
