### ISSUE TITLE
Building instruction

### ISSUE THREAD

**Issue by medvector** [evgraph/CheckIOPyCharmPlugin#53]
Please write instruction about how to build and run this plugin with EDU.

**Comment by medvector** [comment]
I can't see anything about adding educational.jar and interactive-learning.jar to project SDK.
I think that this information definitely should be added to instuctions.

P.S. Is it possible to give me appropriate rights for this repository? I'd like at least to be able to set assignee and reopen issues.

**Comment by evgraph** [comment]
Add info about adding plugins to classpath
332bfb8b4c15a23f0d8d1efa565c54d4378b4a22

**Comment by medvector** [comment]
I really like the way it looks now with screenshot :)
