### ISSUE TITLE
After restart/reopen project plugin don't work

### ISSUE THREAD

**Issue by Derik117** [evgraph/CheckIOPyCharmPlugin#73]
Create new project with CheckIO plugin, successful authorized, run project - i'll see normal my unsolved task and can run it. But after restart PyCharm or reopen project i see raw data folder.
![image](https://cloud.githubusercontent.com/assets/8479647/17360651/48716f3e-5975-11e6-9ba1-09edbaa3c1a9.png)
Reset PyCharm setting doing nothing.
After start new project PyCharm say "Unable to save settings: Failed to save settings. Please restart PyCharm". Buttons get hint, test task etc don't work.
Try on PyCharm Edu and PyCharm 2016.2

**Comment by evgraph** [comment]
Hi!
Thanks for reporting the problem!

Please, attach the log file, you could locate it using Help->Show Log

**Comment by Derik117** [comment]
Hi!
[logs.zip](https://github.com/evgraph/CheckIOPyCharmPlugin/files/400284/logs.zip)

**Comment by evgraph** [comment]
Hi!
I'm sorry for the late answer.
Could you please send me your project just after creation. I'll try to reproduce your problem

**Comment by Derik117** [comment]
Hi :) no problem!
[checkio_project.zip](https://github.com/evgraph/CheckIOPyCharmPlugin/files/412854/checkio_project.zip)

**Comment by evgraph** [comment]
Hi, @Derik117 !
We've released a version of the plugin, that fixes your problem too. You could download an update [here](http://evgraph.github.io/CheckIOPyCharmPlugin/), you need 1.0.9 version.

I'm really sorry for such a late fix, thanks a lot for waiting!
