### ISSUE TITLE
??? instead a cyrillic symbols(Russian)

### ISSUE THREAD

**Issue by Derik117** [evgraph/CheckIOPyCharmPlugin#74]
Last version of pycharm and plugin. In code editor cyrillic symbols looks good, but in task window i see that:
![image](https://cloud.githubusercontent.com/assets/8479647/19308137/bf55cf1c-9086-11e6-956f-965f81f6744f.png)

And after i change language in Settings -> Other Settings -> CheckIO Setting - nothing changed. Only way to change language - recreate project.

Thanks!

**Comment by evgraph** [comment]
Hi, @Derik117!
Thank you for reporting the problem!
Yes, now language setting affect only newly downloaded stations. I'll think to change this behaviour

Could you please attach log file (Help->Show Logs In...) and your project with the encoding problem.
Thank you in advance!

**Comment by Derik117** [comment]
[idea.txt](https://github.com/evgraph/CheckIOPyCharmPlugin/files/524579/idea.txt)

**Comment by evgraph** [comment]
Please, check the latest (1.0.11) version of the plugin: https://plugins.jetbrains.com/plugin/7991?pr=pycharm

**Comment by Derik117** [comment]
It works! Thanks!

UPD: It works after launch, but another task dont work :( If i reopen project - current task works fine, but if i select another task i see that, and first task dont work too.
![image](https://cloud.githubusercontent.com/assets/8479647/19322931/8adeb5e0-90c3-11e6-9ec8-a5157084bbe5.png)
![image](https://cloud.githubusercontent.com/assets/8479647/19322293/196eb3e4-90c1-11e6-83a2-23685392e9b9.png)
![image](https://cloud.githubusercontent.com/assets/8479647/19322304/24391058-90c1-11e6-81d5-d74344dbe23d.png)
[idea.txt](https://github.com/evgraph/CheckIOPyCharmPlugin/files/525331/idea.txt)

**Comment by Derik117** [comment]
up..?

**Comment by evgraph** [comment]
@Derik117, I'm sorry, I didn't see your update message. I'll take a look

**Comment by evgraph** [comment]
I've updated the plugin. 
Please, check the latest (1.0.12) version of the plugin: https://plugins.jetbrains.com/plugin/7991?pr=pycharm

**Comment by Derik117** [comment]
@evgraph Thanks!
